### PR TITLE
Generator

### PR DESCRIPTION
**Pull request by malonej501**
Added generator class to produces successive iterations given an lsystem, axiom and no.steps. The generate_tortoise function translates the string generated by a particular alphabet into tortoise movements. I also altered the tortoise history, such that the angle is recorded for every state.

There are some conflicts with dev branch, so it would be good to know what you think, or if anything needs changing.

### CODE REVIEW

**Comment by TIF141** [comment]
I think the tortoise tests are failing because I get the min and max coords to work out the area which needs to be plotted, so having the angle in there probably conflicts with that

**Comment by TIF141** [comment]
When appending to the history, is has to be history[-1].append. That's 'cause `history` looks like [[[c1, c2], [c3, c4]], [[c5, c6], [c7, [c8]]], where each 'chunk' (`history[0]`, `history[1]`, etc.) are the different continuous sets of points

**Comment by malonej501** [comment]
Ah I see, I could change the expected array in the test to be [[1, 0, 0], [2, 0, 0,]] to include the angle

**Comment by TIF141** [comment]
Ah yes that would work

**Comment by TIF141** [comment]
Sorry, thought it was a different test that was failing

**Comment by malonej501** [comment]
Hm, one of the tortoise tests is still failing - test_history_nodraw_then_draw. I don't really understand why the array the tortoise generates has 4 rows, given that it only moves forward twice, and doesn't change angle?

**Comment by TIF141** [comment]
mm ok so I think you don't have the most up-to-date version of tortoise and tortoise_tests. I changed them before comitting to dev with the image generation and the fixed history generation so that could be it. Have you pulled from dev?

**Comment by malonej501** [comment]
Ah ok that would make sense, I'll have a look at the latest version of dev

**Comment by malonej501** [comment]
is there a way to update my branch with the latest version of tortoise from dev - or perhaps I should just merge, use the latest version of tortoise from dev and resolve any bugs from there on the dev branch directly?

**Comment by TIF141** [comment]
Depends, but if you're happy getting everything from dev onto your branch, you can `git pull` then (on your branch) `git merge dev` which will bring in all the changes. If you have teh git extension, VS Code should show you any merge conflicts

**Comment by malonej501** [comment]
Ok I'm merging the latest version of dev onto the generator branch

**Comment by malonej501** [comment]
Merged the latest changes from the dev branch, looks like it's passing all the tests now, so I can merge unless you think anything else needs changing?

**Review by TIF141 — APPROVED** [review]
Looks good! :D

**Pull request merged**
